DROP TABLE IF EXISTS country_codes;
CREATE TABLE country_codes(
   "Number" INTEGER(3) NOT NULL
  ,"Code"  VARCHAR(4) NOT NULL PRIMARY KEY
  ,"Country" VARCHAR(37) NOT NULL
);
INSERT INTO country_codes("Number","Code","Country") VALUES (4,'AFG','Afghanistan');
INSERT INTO country_codes("Number","Code","Country") VALUES (8,'ALB','Albania');
INSERT INTO country_codes("Number","Code","Country") VALUES (12,'DZA','Algeria');
INSERT INTO country_codes("Number","Code","Country") VALUES (20,'AND','Andorra');
INSERT INTO country_codes("Number","Code","Country") VALUES (24,'AGO','Angola');
INSERT INTO country_codes("Number","Code","Country") VALUES (28,'ATG','Antigua and Barbuda');
INSERT INTO country_codes("Number","Code","Country") VALUES (32,'ARG','Argentina');
INSERT INTO country_codes("Number","Code","Country") VALUES (51,'ARM','Armenia');
INSERT INTO country_codes("Number","Code","Country") VALUES (36,'AUS','Australia');
INSERT INTO country_codes("Number","Code","Country") VALUES (40,'AUT','Austria');
INSERT INTO country_codes("Number","Code","Country") VALUES (31,'AZE','Azerbaijan');
INSERT INTO country_codes("Number","Code","Country") VALUES (44,'BHS','Bahamas');
INSERT INTO country_codes("Number","Code","Country") VALUES (48,'BHR','Bahrain');
INSERT INTO country_codes("Number","Code","Country") VALUES (50,'BGD','Bangladesh');
INSERT INTO country_codes("Number","Code","Country") VALUES (52,'BRB','Barbados');
INSERT INTO country_codes("Number","Code","Country") VALUES (112,'BLR','Belarus');
INSERT INTO country_codes("Number","Code","Country") VALUES (56,'BEL','Belgium');
INSERT INTO country_codes("Number","Code","Country") VALUES (84,'BLZ','Belize');
INSERT INTO country_codes("Number","Code","Country") VALUES (204,'BEN','Benin');
INSERT INTO country_codes("Number","Code","Country") VALUES (64,'BTN','Bhutan');
INSERT INTO country_codes("Number","Code","Country") VALUES (68,'BOL','Bolivia');
INSERT INTO country_codes("Number","Code","Country") VALUES (70,'BIH','Bosnia and Herzegovina');
INSERT INTO country_codes("Number","Code","Country") VALUES (72,'BWA','Botswana');
INSERT INTO country_codes("Number","Code","Country") VALUES (76,'BRA','Brazil');
INSERT INTO country_codes("Number","Code","Country") VALUES (96,'BRN','Brunei Darussalam');
INSERT INTO country_codes("Number","Code","Country") VALUES (100,'BGR','Bulgaria');
INSERT INTO country_codes("Number","Code","Country") VALUES (854,'BFA','Burkina Faso');
INSERT INTO country_codes("Number","Code","Country") VALUES (108,'BDI','Burundi');
INSERT INTO country_codes("Number","Code","Country") VALUES (132,'CPV','Cabo Verde');
INSERT INTO country_codes("Number","Code","Country") VALUES (116,'KHM','Cambodia');
INSERT INTO country_codes("Number","Code","Country") VALUES (120,'CMR','Cameroon');
INSERT INTO country_codes("Number","Code","Country") VALUES (124,'CAN','Canada');
INSERT INTO country_codes("Number","Code","Country") VALUES (140,'CAF','Central African Republic');
INSERT INTO country_codes("Number","Code","Country") VALUES (148,'TCD','Chad');
INSERT INTO country_codes("Number","Code","Country") VALUES (152,'CHL','Chile');
INSERT INTO country_codes("Number","Code","Country") VALUES (156,'CHN','China');
INSERT INTO country_codes("Number","Code","Country") VALUES (170,'COL','Colombia');
INSERT INTO country_codes("Number","Code","Country") VALUES (174,'COM','Comoros');
INSERT INTO country_codes("Number","Code","Country") VALUES (178,'COG','Congo');
INSERT INTO country_codes("Number","Code","Country") VALUES (184,'COK','Cook Islands');
INSERT INTO country_codes("Number","Code","Country") VALUES (188,'CRI','Costa Rica');
INSERT INTO country_codes("Number","Code","Country") VALUES (191,'HRV','Croatia');
INSERT INTO country_codes("Number","Code","Country") VALUES (192,'CUB','Cuba');
INSERT INTO country_codes("Number","Code","Country") VALUES (196,'CYP','Cyprus');
INSERT INTO country_codes("Number","Code","Country") VALUES (203,'CZE','Czech Republic');
INSERT INTO country_codes("Number","Code","Country") VALUES (384,'CIV','Côte d''Ivoire');
INSERT INTO country_codes("Number","Code","Country") VALUES (408,'PRK','Democratic People''s Republic of Korea');
INSERT INTO country_codes("Number","Code","Country") VALUES (180,'COD','Democratic Republic of the Congo');
INSERT INTO country_codes("Number","Code","Country") VALUES (208,'DNK','Denmark');
INSERT INTO country_codes("Number","Code","Country") VALUES (262,'DJI','Djibouti');
INSERT INTO country_codes("Number","Code","Country") VALUES (212,'DMA','Dominica');
INSERT INTO country_codes("Number","Code","Country") VALUES (214,'DOM','Dominican Republic');
INSERT INTO country_codes("Number","Code","Country") VALUES (218,'ECU','Ecuador');
INSERT INTO country_codes("Number","Code","Country") VALUES (818,'EGY','Egypt');
INSERT INTO country_codes("Number","Code","Country") VALUES (222,'SLV','El Salvador');
INSERT INTO country_codes("Number","Code","Country") VALUES (226,'GNQ','Equatorial Guinea');
INSERT INTO country_codes("Number","Code","Country") VALUES (232,'ERI','Eritrea');
INSERT INTO country_codes("Number","Code","Country") VALUES (233,'EST','Estonia');
INSERT INTO country_codes("Number","Code","Country") VALUES (231,'ETH','Ethiopia');
INSERT INTO country_codes("Number","Code","Country") VALUES (242,'FJI','Fiji');
INSERT INTO country_codes("Number","Code","Country") VALUES (246,'FIN','Finland');
INSERT INTO country_codes("Number","Code","Country") VALUES (250,'FRA','France');
INSERT INTO country_codes("Number","Code","Country") VALUES (266,'GAB','Gabon');
INSERT INTO country_codes("Number","Code","Country") VALUES (270,'GMB','Gambia');
INSERT INTO country_codes("Number","Code","Country") VALUES (268,'GEO','Georgia');
INSERT INTO country_codes("Number","Code","Country") VALUES (276,'DEU','Germany');
INSERT INTO country_codes("Number","Code","Country") VALUES (288,'GHA','Ghana');
INSERT INTO country_codes("Number","Code","Country") VALUES (300,'GRC','Greece');
INSERT INTO country_codes("Number","Code","Country") VALUES (308,'GRD','Grenada');
INSERT INTO country_codes("Number","Code","Country") VALUES (320,'GTM','Guatemala');
INSERT INTO country_codes("Number","Code","Country") VALUES (324,'GIN','Guinea');
INSERT INTO country_codes("Number","Code","Country") VALUES (624,'GNB','Guinea-Bissau');
INSERT INTO country_codes("Number","Code","Country") VALUES (328,'GUY','Guyana');
INSERT INTO country_codes("Number","Code","Country") VALUES (332,'HTI','Haiti');
INSERT INTO country_codes("Number","Code","Country") VALUES (340,'HND','Honduras');
INSERT INTO country_codes("Number","Code","Country") VALUES (348,'HUN','Hungary');
INSERT INTO country_codes("Number","Code","Country") VALUES (352,'ISL','Iceland');
INSERT INTO country_codes("Number","Code","Country") VALUES (356,'IND','India');
INSERT INTO country_codes("Number","Code","Country") VALUES (360,'IDN','Indonesia');
INSERT INTO country_codes("Number","Code","Country") VALUES (364,'IRN','Iran');
INSERT INTO country_codes("Number","Code","Country") VALUES (368,'IRQ','Iraq');
INSERT INTO country_codes("Number","Code","Country") VALUES (372,'IRL','Ireland');
INSERT INTO country_codes("Number","Code","Country") VALUES (376,'ISR','Israel');
INSERT INTO country_codes("Number","Code","Country") VALUES (380,'ITA','Italy');
INSERT INTO country_codes("Number","Code","Country") VALUES (388,'JAM','Jamaica');
INSERT INTO country_codes("Number","Code","Country") VALUES (392,'JPN','Japan');
INSERT INTO country_codes("Number","Code","Country") VALUES (400,'JOR','Jordan');
INSERT INTO country_codes("Number","Code","Country") VALUES (398,'KAZ','Kazakhstan');
INSERT INTO country_codes("Number","Code","Country") VALUES (404,'KEN','Kenya');
INSERT INTO country_codes("Number","Code","Country") VALUES (296,'KIR','Kiribati');
INSERT INTO country_codes("Number","Code","Country") VALUES (414,'KWT','Kuwait');
INSERT INTO country_codes("Number","Code","Country") VALUES (417,'KGZ','Kyrgyzstan');
INSERT INTO country_codes("Number","Code","Country") VALUES (418,'LAO','Laos');
INSERT INTO country_codes("Number","Code","Country") VALUES (428,'LVA','Latvia');
INSERT INTO country_codes("Number","Code","Country") VALUES (422,'LBN','Lebanon');
INSERT INTO country_codes("Number","Code","Country") VALUES (426,'LSO','Lesotho');
INSERT INTO country_codes("Number","Code","Country") VALUES (430,'LBR','Liberia');
INSERT INTO country_codes("Number","Code","Country") VALUES (434,'LBY','Libya');
INSERT INTO country_codes("Number","Code","Country") VALUES (440,'LTU','Lithuania');
INSERT INTO country_codes("Number","Code","Country") VALUES (442,'LUX','Luxembourg');
INSERT INTO country_codes("Number","Code","Country") VALUES (807,'MKD','Macdeonia');
INSERT INTO country_codes("Number","Code","Country") VALUES (450,'MDG','Madagascar');
INSERT INTO country_codes("Number","Code","Country") VALUES (454,'MWI','Malawi');
INSERT INTO country_codes("Number","Code","Country") VALUES (458,'MYS','Malaysia');
INSERT INTO country_codes("Number","Code","Country") VALUES (462,'MDV','Maldives');
INSERT INTO country_codes("Number","Code","Country") VALUES (466,'MLI','Mali');
INSERT INTO country_codes("Number","Code","Country") VALUES (470,'MLT','Malta');
INSERT INTO country_codes("Number","Code","Country") VALUES (584,'MHL','Marshall Islands');
INSERT INTO country_codes("Number","Code","Country") VALUES (478,'MRT','Mauritania');
INSERT INTO country_codes("Number","Code","Country") VALUES (480,'MUS','Mauritius');
INSERT INTO country_codes("Number","Code","Country") VALUES (484,'MEX','Mexico');
INSERT INTO country_codes("Number","Code","Country") VALUES (583,'FSM','Micronesia');
INSERT INTO country_codes("Number","Code","Country") VALUES (498,'MDA','Moldova');
INSERT INTO country_codes("Number","Code","Country") VALUES (492,'MCO','Monaco');
INSERT INTO country_codes("Number","Code","Country") VALUES (496,'MNG','Mongolia');
INSERT INTO country_codes("Number","Code","Country") VALUES (499,'MNE','Montenegro');
INSERT INTO country_codes("Number","Code","Country") VALUES (504,'MAR','Morocco');
INSERT INTO country_codes("Number","Code","Country") VALUES (508,'MOZ','Mozambique');
INSERT INTO country_codes("Number","Code","Country") VALUES (104,'MMR','Myanmar');
INSERT INTO country_codes("Number","Code","Country") VALUES (516,'NAM','Namibia');
INSERT INTO country_codes("Number","Code","Country") VALUES (520,'NRU','Nauru');
INSERT INTO country_codes("Number","Code","Country") VALUES (524,'NPL','Nepal');
INSERT INTO country_codes("Number","Code","Country") VALUES (528,'NLD','Netherlands');
INSERT INTO country_codes("Number","Code","Country") VALUES (554,'NZL','New Zealand');
INSERT INTO country_codes("Number","Code","Country") VALUES (558,'NIC','Nicaragua');
INSERT INTO country_codes("Number","Code","Country") VALUES (562,'NER','Niger');
INSERT INTO country_codes("Number","Code","Country") VALUES (566,'NGA','Nigeria');
INSERT INTO country_codes("Number","Code","Country") VALUES (570,'NIU','Niue');
INSERT INTO country_codes("Number","Code","Country") VALUES (578,'NOR','Norway');
INSERT INTO country_codes("Number","Code","Country") VALUES (512,'OMN','Oman');
INSERT INTO country_codes("Number","Code","Country") VALUES (586,'PAK','Pakistan');
INSERT INTO country_codes("Number","Code","Country") VALUES (585,'PLW','Palau');
INSERT INTO country_codes("Number","Code","Country") VALUES (591,'PAN','Panama');
INSERT INTO country_codes("Number","Code","Country") VALUES (598,'PNG','Papua New Guinea');
INSERT INTO country_codes("Number","Code","Country") VALUES (600,'PRY','Paraguay');
INSERT INTO country_codes("Number","Code","Country") VALUES (604,'PER','Peru');
INSERT INTO country_codes("Number","Code","Country") VALUES (608,'PHL','Philippines');
INSERT INTO country_codes("Number","Code","Country") VALUES (616,'POL','Poland');
INSERT INTO country_codes("Number","Code","Country") VALUES (620,'PRT','Portugal');
INSERT INTO country_codes("Number","Code","Country") VALUES (634,'QAT','Qatar');
INSERT INTO country_codes("Number","Code","Country") VALUES (410,'KOR','Republic of Korea');
INSERT INTO country_codes("Number","Code","Country") VALUES (642,'ROU','Romania');
INSERT INTO country_codes("Number","Code","Country") VALUES (643,'RUS','Russia');
INSERT INTO country_codes("Number","Code","Country") VALUES (646,'RWA','Rwanda');
INSERT INTO country_codes("Number","Code","Country") VALUES (659,'KNA','Saint Kitts and Nevis');
INSERT INTO country_codes("Number","Code","Country") VALUES (662,'LCA','Saint Lucia');
INSERT INTO country_codes("Number","Code","Country") VALUES (670,'VCT','Saint Vincent and the Grenadines');
INSERT INTO country_codes("Number","Code","Country") VALUES (882,'WSM','Samoa');
INSERT INTO country_codes("Number","Code","Country") VALUES (674,'SMR','San Marino');
INSERT INTO country_codes("Number","Code","Country") VALUES (678,'STP','Sao Tome and Principe');
INSERT INTO country_codes("Number","Code","Country") VALUES (682,'SAU','Saudi Arabia');
INSERT INTO country_codes("Number","Code","Country") VALUES (686,'SEN','Senegal');
INSERT INTO country_codes("Number","Code","Country") VALUES (688,'SRB','Serbia');
INSERT INTO country_codes("Number","Code","Country") VALUES (690,'SYC','Seychelles');
INSERT INTO country_codes("Number","Code","Country") VALUES (694,'SLE','Sierra Leone');
INSERT INTO country_codes("Number","Code","Country") VALUES (702,'SGP','Singapore');
INSERT INTO country_codes("Number","Code","Country") VALUES (703,'SVK','Slovakia');
INSERT INTO country_codes("Number","Code","Country") VALUES (705,'SVN','Slovenia');
INSERT INTO country_codes("Number","Code","Country") VALUES (90,'SLB','Solomon Islands');
INSERT INTO country_codes("Number","Code","Country") VALUES (706,'SOM','Somalia');
INSERT INTO country_codes("Number","Code","Country") VALUES (710,'ZAF','South Africa');
INSERT INTO country_codes("Number","Code","Country") VALUES (728,'SSD','South Sudan');
INSERT INTO country_codes("Number","Code","Country") VALUES (724,'ESP','Spain');
INSERT INTO country_codes("Number","Code","Country") VALUES (144,'LKA','Sri Lanka');
INSERT INTO country_codes("Number","Code","Country") VALUES (729,'SDN','Sudan');
INSERT INTO country_codes("Number","Code","Country") VALUES (740,'SUR','Suriname');
INSERT INTO country_codes("Number","Code","Country") VALUES (748,'SWZ','Swaziland');
INSERT INTO country_codes("Number","Code","Country") VALUES (752,'SWE','Sweden');
INSERT INTO country_codes("Number","Code","Country") VALUES (756,'CHE','Switzerland');
INSERT INTO country_codes("Number","Code","Country") VALUES (760,'SYR','Syrian Arab Republic');
INSERT INTO country_codes("Number","Code","Country") VALUES (762,'TJK','Tajikistan');
INSERT INTO country_codes("Number","Code","Country") VALUES (834,'TZA','Tanzania');
INSERT INTO country_codes("Number","Code","Country") VALUES (764,'THA','Thailand');
INSERT INTO country_codes("Number","Code","Country") VALUES (626,'TLS','Timor-Leste');
INSERT INTO country_codes("Number","Code","Country") VALUES (768,'TGO','Togo');
INSERT INTO country_codes("Number","Code","Country") VALUES (776,'TON','Tonga');
INSERT INTO country_codes("Number","Code","Country") VALUES (780,'TTO','Trinidad and Tobago');
INSERT INTO country_codes("Number","Code","Country") VALUES (788,'TUN','Tunisia');
INSERT INTO country_codes("Number","Code","Country") VALUES (792,'TUR','Turkey');
INSERT INTO country_codes("Number","Code","Country") VALUES (795,'TKM','Turkmenistan');
INSERT INTO country_codes("Number","Code","Country") VALUES (798,'TUV','Tuvalu');
INSERT INTO country_codes("Number","Code","Country") VALUES (800,'UGA','Uganda');
INSERT INTO country_codes("Number","Code","Country") VALUES (804,'UKR','Ukraine');
INSERT INTO country_codes("Number","Code","Country") VALUES (784,'ARE','United Arab Emirates');
INSERT INTO country_codes("Number","Code","Country") VALUES (826,'GBR','United Kingdom');
INSERT INTO country_codes("Number","Code","Country") VALUES (840,'USA','Untied States');
INSERT INTO country_codes("Number","Code","Country") VALUES (858,'URY','Uruguay');
INSERT INTO country_codes("Number","Code","Country") VALUES (860,'UZB','Uzbekistan');
INSERT INTO country_codes("Number","Code","Country") VALUES (548,'VUT','Vanuatu');
INSERT INTO country_codes("Number","Code","Country") VALUES (862,'VEN','Venezuela');
INSERT INTO country_codes("Number","Code","Country") VALUES (704,'VNM','Viet Nam');
INSERT INTO country_codes("Number","Code","Country") VALUES (887,'YEM','Yemen');
INSERT INTO country_codes("Number","Code","Country") VALUES (894,'ZMB','Zambia');
INSERT INTO country_codes("Number","Code","Country") VALUES (716,'ZWE','Zimbabwe');
