cda_res = dbSendQuery(db, 'SELECT * FROM cda_long')
cda_df = data.frame(fetch(cda_res, -1))
cda_wide = reshape(cda_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  cda_wide, name = 'cda_wide')
cgdpe_res = dbSendQuery(db, 'SELECT * FROM cgdpe_long')
cgdpe_df = data.frame(fetch(cgdpe_res, -1))
cgdpe_wide = reshape(cgdpe_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  cgdpe_wide, name = 'cgdpe_wide')
cgdpo_res = dbSendQuery(db, 'SELECT * FROM cgdpo_long')
cgdpo_df = data.frame(fetch(cgdpo_res, -1))
cgdpo_wide = reshape(cgdpo_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  cgdpo_wide, name = 'cgdpo_wide')
ck_res = dbSendQuery(db, 'SELECT * FROM ck_long')
ck_df = data.frame(fetch(ck_res, -1))
ck_wide = reshape(ck_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  ck_wide, name = 'ck_wide')
cor_exp_res = dbSendQuery(db, 'SELECT * FROM cor_exp_long')
cor_exp_df = data.frame(fetch(cor_exp_res, -1))
cor_exp_wide = reshape(cor_exp_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  cor_exp_wide, name = 'cor_exp_wide')
csh_c_res = dbSendQuery(db, 'SELECT * FROM csh_c_long')
csh_c_df = data.frame(fetch(csh_c_res, -1))
csh_c_wide = reshape(csh_c_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  csh_c_wide, name = 'csh_c_wide')
csh_g_res = dbSendQuery(db, 'SELECT * FROM csh_g_long')
csh_g_df = data.frame(fetch(csh_g_res, -1))
csh_g_wide = reshape(csh_g_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  csh_g_wide, name = 'csh_g_wide')
csh_i_res = dbSendQuery(db, 'SELECT * FROM csh_i_long')
csh_i_df = data.frame(fetch(csh_i_res, -1))
csh_i_wide = reshape(csh_i_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  csh_i_wide, name = 'csh_i_wide')
csh_m_res = dbSendQuery(db, 'SELECT * FROM csh_m_long')
csh_m_df = data.frame(fetch(csh_m_res, -1))
csh_m_wide = reshape(csh_m_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  csh_m_wide, name = 'csh_m_wide')
csh_r_res = dbSendQuery(db, 'SELECT * FROM csh_r_long')
csh_r_df = data.frame(fetch(csh_r_res, -1))
csh_r_wide = reshape(csh_r_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  csh_r_wide, name = 'csh_r_wide')
csh_x_res = dbSendQuery(db, 'SELECT * FROM csh_x_long')
csh_x_df = data.frame(fetch(csh_x_res, -1))
csh_x_wide = reshape(csh_x_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')	
dbWriteTable(db, value =  csh_x_wide, name = 'csh_x_wide')
ctfp_res = dbSendQuery(db, 'SELECT * FROM ctfp_long')
ctfp_df = data.frame(fetch(ctfp_res, -1))
ctfp_wide = reshape(ctfp_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  ctfp_wide, name = 'ctfp_wide')
cwtfp_res = dbSendQuery(db, 'SELECT * FROM cwtfp_long')
cwtfp_df = data.frame(fetch(cwtfp_res, -1))
cwtfp_wide = reshape(cwtfp_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  cwtfp_wide, name = 'cwtfp_wide')
delta_res = dbSendQuery(db, 'SELECT * FROM delta_long')
delta_df = data.frame(fetch(delta_res, -1))
delta_wide = reshape(delta_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  delta_wide, name = 'delta_wide')
emp_res = dbSendQuery(db, 'SELECT * FROM emp_long')
emp_df = data.frame(fetch(emp_res, -1))
emp_wide = reshape(emp_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  emp_wide, name = 'emp_wide')
hc_res = dbSendQuery(db, 'SELECT * FROM hc_long')
hc_df = data.frame(fetch(hc_res, -1))
hc_wide = reshape(hc_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  hc_wide, name = 'hc_wide')
i_cig_res = dbSendQuery(db, 'SELECT * FROM i_cig_long')
i_cig_df = data.frame(fetch(i_cig_res, -1))
i_cig_wide = reshape(i_cig_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  i_cig_wide, name = 'i_cig_wide')
i_outlier_res = dbSendQuery(db, 'SELECT * FROM i_outlier_long')
i_outlier_df = data.frame(fetch(i_outlier_res, -1))
i_outlier_wide = reshape(i_outlier_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  i_outlier_wide, name = 'i_outlier_wide')
i_xm_res = dbSendQuery(db, 'SELECT * FROM i_xm_long')
i_xm_df = data.frame(fetch(i_xm_res, -1))
i_xm_wide = reshape(i_xm_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  i_xm_wide, name = 'i_xm_wide')
i_xr_res = dbSendQuery(db, 'SELECT * FROM i_xr_long')
i_xr_df = data.frame(fetch(i_xr_res, -1))
i_xr_wide = reshape(i_xr_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  i_xr_wide, name = 'i_xr_wide')
labsh_res = dbSendQuery(db, 'SELECT * FROM labsh_long')
labsh_df = data.frame(fetch(labsh_res, -1))
labsh_wide = reshape(labsh_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  labsh_wide, name = 'labsh_wide')
pl_c_res = dbSendQuery(db, 'SELECT * FROM pl_c_long')
pl_c_df = data.frame(fetch(pl_c_res, -1))
pl_c_wide = reshape(pl_c_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_c_wide, name = 'pl_c_wide')
pl_con_res = dbSendQuery(db, 'SELECT * FROM pl_con_long')
pl_con_df = data.frame(fetch(pl_con_res, -1))
pl_con_wide = reshape(pl_con_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_con_wide, name = 'pl_con_wide')
pl_da_res = dbSendQuery(db, 'SELECT * FROM pl_da_long')
pl_da_df = data.frame(fetch(pl_da_res, -1))
pl_da_wide = reshape(pl_da_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_da_wide, name = 'pl_da_wide')
pl_g_res = dbSendQuery(db, 'SELECT * FROM pl_g_long')
pl_g_df = data.frame(fetch(pl_g_res, -1))
pl_g_wide = reshape(pl_g_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_g_wide, name = 'pl_g_wide')
pl_gdpo_res = dbSendQuery(db, 'SELECT * FROM pl_gdpo_long')
pl_gdpo_df = data.frame(fetch(pl_gdpo_res, -1))
pl_gdpo_wide = reshape(pl_gdpo_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')	
dbWriteTable(db, value =  pl_gdpo_wide, name = 'pl_gdpo_wide')
pl_i_res = dbSendQuery(db, 'SELECT * FROM pl_i_long')
pl_i_df = data.frame(fetch(pl_i_res, -1))
pl_i_wide = reshape(pl_i_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_i_wide, name = 'pl_i_wide')
pl_k_res = dbSendQuery(db, 'SELECT * FROM pl_k_long')
pl_k_df = data.frame(fetch(pl_k_res, -1))
pl_k_wide = reshape(pl_k_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_k_wide, name = 'pl_k_wide')
pl_m_res = dbSendQuery(db, 'SELECT * FROM pl_m_long')
pl_m_df = data.frame(fetch(pl_m_res, -1))
pl_m_wide = reshape(pl_m_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_m_wide, name = 'pl_m_wide')
pl_x_res = dbSendQuery(db, 'SELECT * FROM pl_x_long')
pl_x_df = data.frame(fetch(pl_x_res, -1))
pl_x_wide = reshape(pl_x_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pl_x_wide, name = 'pl_x_wide')
pop_res = dbSendQuery(db, 'SELECT * FROM pop_long')
pop_df = data.frame(fetch(pop_res, -1))
pop_wide = reshape(pop_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  pop_wide, name = 'pop_wide')
rconna_res = dbSendQuery(db, 'SELECT * FROM rconna_long')
rconna_df = data.frame(fetch(rconna_res, -1))
rconna_wide = reshape(rconna_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rconna_wide, name = 'rconna_wide')
rdana_res = dbSendQuery(db, 'SELECT * FROM rdana_long')
rdana_df = data.frame(fetch(rdana_res, -1))
rdana_wide = reshape(rdana_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rdana_wide, name = 'rdana_wide')
rgdpe_res = dbSendQuery(db, 'SELECT * FROM rgdpe_long')
rgdpe_df = data.frame(fetch(rgdpe_res, -1))
rgdpe_wide = reshape(rgdpe_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rgdpe_wide, name = 'rgdpe_wide')
rgdpna_res = dbSendQuery(db, 'SELECT * FROM rgdpna_long')
rgdpna_df = data.frame(fetch(rgdpna_res, -1))
rgdpna_wide = reshape(rgdpna_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rgdpna_wide, name = 'rgdpna_wide')
rgdpo_res = dbSendQuery(db, 'SELECT * FROM rgdpo_long')
rgdpo_df = data.frame(fetch(rgdpo_res, -1))
rgdpo_wide = reshape(rgdpo_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rgdpo_wide, name = 'rgdpo_wide')
rkna_res = dbSendQuery(db, 'SELECT * FROM rkna_long')
rkna_df = data.frame(fetch(rkna_res, -1))
rkna_wide = reshape(rkna_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rkna_wide, name = 'rkna_wide')
rtfpna_res = dbSendQuery(db, 'SELECT * FROM rtfpna_long')
rtfpna_df = data.frame(fetch(rtfpna_res, -1))
rtfpna_wide = reshape(rtfpna_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rtfpna_wide, name = 'rtfpna_wide')
rwtfpna_res = dbSendQuery(db, 'SELECT * FROM rwtfpna_long')
rwtfpna_df = data.frame(fetch(rwtfpna_res, -1))
rwtfpna_wide = reshape(rwtfpna_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  rwtfpna_wide, name = 'rwtfpna_wide')
statcap_res = dbSendQuery(db, 'SELECT * FROM statcap_long')
statcap_df = data.frame(fetch(statcap_res, -1))
statcap_wide = reshape(statcap_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  statcap_wide, name = 'statcap_wide')
xr_res = dbSendQuery(db, 'SELECT * FROM xr_long')
xr_df = data.frame(fetch(xr_res, -1))
xr_wide = reshape(xr_df, timevar  = 'year', idvar = 'country_code', direction = 'wide')
dbWriteTable(db, value =  xr_wide, name = 'xr_wide')